kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-pgbench-sc
  namespace: kube-system
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
allowVolumeExpansion: true
